### ISSUE TITLE
Optimize tuple projections in the Haskell backend/pretty-printer

### ISSUE THREAD

**Issue by ckoparkar** [iu-parfunc/gibbon#111]
Consider this Gibbon AST:

```Haskell
let tup :: (T1, T2, T3) = EXP in
... (proj 0 tup) ... (proj 1 tup) ...
```

Gibbon would translate it to this Haskell code:

```Haskell
let tup :: (T1, T2, T3) = EXP in
... (let (a,_,_) = tup in a) ... (let (_,_b,_) = tup in b) ...
```

Instead, we'd like to have:

```Haskell
let (a,b,c) :: (T1,T2,T3) = EXP in
... a ... b ...
```

(reported by @laithsakka on Slack)

**Comment by vollmerm** [comment]
Is this a readability thing, or does it actually affect performance?

**Comment by ckoparkar** [comment]
It definitely improves readability.

@laithsakka's main intention behind proposing this is to improve performance I think. On the Hangouts call, he said that he did a bunch of optimizations at once, so he doesn't have the numbers for this specific one. 

But I think that if we only have one pattern match, GHC would evaluate the outermost thunk only once - as opposed to doing it multiple times (once for every pattern match). So it might improve performance, especially if we end up using these pattern matches a lot. Does this sound right @rrnewton ?

**Comment by vollmerm** [comment]
I asked because I'm actually not sure. I don't know enough about how GHC compiles pattern matching. It's possible the extra work gets optimized away.

Anyway, a simple greedy approach where we collect a series of projections that happen in a row into one pattern match shouldn't be too hard to add. A more sophisticated approach would collect *all* projections of a value into a single statement, which kind of reminds me of the approach `inferLocations` takes where it finds all projections and lifts them up to right after the binding of the tuple value.

**Comment by ckoparkar** [comment]
I was actually thinking of using substitution for this:

Gibbon AST:

```Haskell
let tup :: (T1,T2,T3) = EXP in
... (proj 0 tup) ... (proj 1 tup) ...
```

wold become:

```Haskell
let tup :: (T1,T2,T3) = EXP in
let (a,b,c) = tup in
... (substE (proj 0 tup) a) ... 
```

`Fusion2` already inlines these projections into expressions.
